import type { RulePack } from './types';
import { validateRulePack } from './types';

export const niAct138: RulePack = validateRulePack({
  id: 'ni-act-138',
  version: '2026-09-20.1',
  title: 'Cheque dishonour',
  jurisdiction: 'India',
  scope: 'A worked arithmetic chain for reviewed NI Act sections 138 and 142.',
  warning: 'Legal information only. Trigger selection and legal characterisation remain external.',
  anchors: [
    {
      id: 'cheque_date',
      eventKind: 'cheque_date',
      label: 'Date shown on the cheque',
      legalPhrase: 'date of the cheque',
      evidenceExamples: ['Cheque image or counterfoil'],
      required: false,
    },
    {
      id: 'bank_information_received',
      eventKind: 'bank_information_received',
      label: 'Bank information received',
      legalPhrase: 'receipt of information from the bank regarding return of the cheque',
      evidenceExamples: ['Return memo', 'Bank message paired with account record'],
      required: true,
    },
    {
      id: 'demand_notice_dispatched',
      eventKind: 'demand_notice_dispatched',
      label: 'Demand notice dispatched',
      legalPhrase: 'dispatch of the written demand notice',
      evidenceExamples: ['Postal receipt', 'Courier booking record'],
      required: false,
    },
    {
      id: 'demand_notice_received_by_drawer',
      eventKind: 'demand_notice_received_by_drawer',
      label: 'Demand notice received by drawer',
      legalPhrase: 'receipt of the notice by the drawer',
      evidenceExamples: ['Delivery tracking', 'Acknowledgement of service'],
      required: true,
    },
  ],
  steps: [
    {
      id: 'notice_boundary',
      label: 'Notice-period boundary',
      provision: 'Negotiable Instruments Act 1881, section 138(b)',
      sourceRef: 'ni-act-138-b',
      inputs: [{ ref: 'bank_information_received', required: true }],
      operation: { kind: 'add_days', amount: 30 },
      missingEvidence: 'A confirmed date for receipt of information from the bank.',
      caveats: ['No court-holiday or statutory-exclusion adjustment is applied.'],
    },
    {
      id: 'payment_period_boundary',
      label: 'Payment-period boundary',
      provision: 'Negotiable Instruments Act 1881, section 138(c)',
      sourceRef: 'ni-act-138-c',
      inputs: [{ ref: 'demand_notice_received_by_drawer', required: true }],
      operation: { kind: 'add_days', amount: 15 },
      missingEvidence: 'A confirmed record of receipt of the notice by the drawer.',
      caveats: ['Dispatch is not substituted for receipt.'],
    },
    {
      id: 'cause_of_action_date',
      label: 'Next-day cause-of-action date',
      provision: 'Negotiable Instruments Act 1881, sections 138(c) and 142(1)(b)',
      sourceRef: 'ni-act-142-1-b',
      inputs: [{ ref: 'payment_period_boundary', required: true }],
      operation: { kind: 'next_day' },
      missingEvidence: 'The payment-period boundary must be bound first.',
      caveats: ['This is a mechanical next-day derivation.'],
    },
    {
      id: 'complaint_boundary',
      label: 'Complaint-period boundary',
      provision: 'Negotiable Instruments Act 1881, section 142(1)(b)',
      sourceRef: 'ni-act-142-1-b',
      inputs: [{ ref: 'cause_of_action_date', required: true }],
      operation: { kind: 'add_months', amount: 1 },
      missingEvidence: 'The cause-of-action date must be bound first.',
      caveats: [
        'A calendar month is used, not 30 days.',
        'Condonation, exclusions, and court-closure rules are not evaluated.',
      ],
    },
  ],
  sourceRefs: ['ni-act-138-b', 'ni-act-138-c', 'ni-act-142-1-b'],
  caveats: [
    'Cheque presentation validity is governed by a separate RBI direction and is not calculated.',
    'The amount demanded is not compared with the cheque amount.',
  ],
});
